### ISSUE TITLE
saw no other way to contact you: this is about your "pinyin on top of hanzi" anki addon

### ISSUE THREAD

**Issue by mcBaum** [ericahn/anki-addon-jupyter#1]
hey, i've recently started using your "pinyin on top of hanzi" anki addon https://ankiweb.net/shared/info/417709332

i've wondered if i could extend it in a way where the display of pinyin is optional (like in jp-mining notes) and/or the pinyin is saved seperately from the hanzi so you don't have to generate it anew every time. however, you either deleted the repository or made it private. is there a possibility you could make it public again?

thanks, mc

**Comment by ericahn** [comment]
Hi, I've made the repo public

**Comment by mcBaum** [comment]
awesome thanks a lot! i forked it but i'll have to see when i have time to work on it as i recently got a full time job again :')
